# The default config that will be merged with the mode config [development, production, test] and then local.yaml.

############################
# homekit config.
############################
homekit:
  setup:
    serial: F1:F6:AC:2B:7E:8B
    pin: 069-39-561
    port: 25777
    insecure: true # allow insecure access?
  accessories:
    - accessory: SamsungTV
      name: UE42
      ip_address: 10.0.0.32
    - accessory: Plex
      name: Plex
      plex_token: CYjxgRwttBuPjChZH6ty
      debug: true
      filter:
        - user: bonesoul
        - player: "TV QE65Q70RATXTK"
  platforms:
    - platform: config
      name: Config
      port: 8581,
      auth: none,
      theme: auto,
      tempUnits: c
      noFork: true
      logs:
        method: file
        path: C:/Users/shala/.homer/logs/homer.log
    - platform: Hue
      name: Hue
      lights: true
      forceCt: true
      nativeHomeKitLights: false
      nativeHomeKitSensors: true
      nupnp: true
      resource: true
      sensors: false
      anyOn: true
      users:
        001788FFFE4E4B97: iNPI0C1c3B8TRQjYIXWSfGR7umtIPr9gSYhssmp4

############################
# Logging config.
############################
logging:
  master:
    console: # console logging.
      enabled: true # enable console log?
      level: silly #  minimum log level.
    file: # file logging.
      enabled: true # enable logging to file?
      level: silly # minimum log level.
  plugin: # per-plugin loggers
    console: # console logging.
      enabled: true # enable console log?
      level: silly # minimum log level
    file: # file logging.
      enabled: true # enable logging to file?
      level: silly # minimum log level.