############################
# Logging config.
############################
logs:
  master:
    console: # console logging.
      enabled: true # enable console log?
      level: verbose #  minimum log level.
    file: # file logging.
      enabled: true # enable loggin to file?
      level: verbose # minimum log level.
  jobs:
    console: # console logging.
      enabled: true # enable console log?
      level: verbose #  minimum log level.
    file: # file logging.
      enabled: true # enable loggin to file?
      level: verbose # minimum log level.

