logs:
  master:
    console:
      enabled: true
      level: info
    file:
      enabled: true
      level: debug
  jobs:
    console:
      enabled: false
      level: info
    file:
      enabled: true
      level: debug
