name: dotnet-core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install dotnet core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    #- name: run mongodb
    #  run:  sudo docker run --name mongo -d -p 27017:27017 mongo    
    - name: build
      run: ./build.sh
    - name: test
      run: dotnet test
